name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get changed Dockerfile
      id: changed-files-specific
      uses: tj-actions/changed-files@v34
      with:
        files: |
          ./Dockerfile
    
    - uses: actions/checkout@v3
    - name: Build the Docker image
      if: steps.changed-files-specific.outputs.any_changed == 'true'
      run: docker build . --file Dockerfile --tag greenapi/whatsapp-api-webhook-server-python:latest
      
    - name: Login to Docker Hub
      if: steps.changed-files-specific.outputs.any_changed == 'true'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
          
    - name: Publish the Docker image
      if: steps.changed-files-specific.outputs.any_changed == 'true'
      run: docker push greenapi/whatsapp-api-webhook-server-python:latest
