name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check if there are changes
      id: changes
      uses: UnicornGlobal/has-changes-action@v1.0.11
    
    - uses: actions/checkout@v3
    - name: Build the Docker image
      if: steps.changes.outputs.changed == 1
      run: docker build . --file Dockerfile --tag greenapi/whatsapp-api-webhook-server-python:latest
      
    - name: Login to Docker Hub
      if: steps.changes.outputs.changed == 1
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
          
    - name: Publish the Docker image
      if: steps.changes.outputs.changed == 1
      run: docker push greenapi/whatsapp-api-webhook-server-python:latest
